version: '3'
services:
  app:
    image: app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
